version: '3'

services:
  # App
  api:
    container_name: FastAPI
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend/app:/app
    environment:
        - GRAPH_DB_HOST=neo4j
        - GRAPH_DB_PORT=7687
        - GRAPH_DB_USER=neo4j
        - GRAPH_DB_PASSWORD=neo4jj
  
  # Nginx
  nginx01:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./container/nginx/01/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./container/nginx/01/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./container/nginx/01/log:/var/log/nginx
  nginx02:
    image: nginx:latest
    # ports:
    #   - "8082:8080"
    volumes:
      - ./container/nginx/02/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./container/nginx/02/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./container/nginx/02/log:/var/log/nginx
  
  # Fluentd
  fluentd01:
    image: fluent/fluentd:v1.15.0-1.0
    # ports:
    #   - 24225:24224
    volumes:
      - ./container/fluentd/01/fluent.conf:/fluentd/etc/fluent.conf
      - ./container/nginx/01/log:/var/log/nginx
  fluentd02:
    image: fluent/fluentd:v1.15.0-1.0
    # ports:
    #   - 24226:24224
    volumes:
      - ./container/fluentd/02/fluent.conf:/fluentd/etc/fluent.conf
      - ./container/nginx/02/log:/var/log/nginx
  
  # datastore
  neo4j:
    container_name: neo4j
    image: neo4j
    ports:
        - 7474:7474
        - 7687:7687
    volumes: 
        - neo4j-data:/data
        - neo4j-logs:/logs
        - neo4j-conf:/conf
    environment:
        - NEO4J_AUTH=neo4j/neo4jj

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-conf:
