version: '3'

services:
  api:
    container_name: FastAPI
    build: ./api
    ports:
      - "80:80"
    volumes:
      - ./api/app:/app
  nginx:
    image: nginx:latest
    container_name: nginx01
    ports:
      - "8080:8080"
    volumes:
      - ./container/nginx/01/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./container/nginx/01/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./container/nginx/01/log:/var/log/nginx
  fluentd:
    image: fluent/fluentd:v1.15.0-1.0
    ports:
      - 24224:24224
    volumes:
      - ./container/fluentd/01/fluent.conf:/fluentd/etc/fluent.conf
      - ./container/fluentd/01/log:/var/log/fluent
      - ./container/nginx/01/log:/var/log/nginx


#   neo4j:
#     container_name: neo4j
#     image: neo4j
#     ports:
#         - 7474:7474
#         - 7687:7687
#     volumes: 
#         - neo4j-data:/data
#         - neo4j-logs:/logs
#         - neo4j-conf:/conf
#     environment:
#         - NEO4J_AUTH=neo4j/neo4jj

# volumes:
#   neo4j-data:
#   neo4j-logs:
#   neo4j-conf:
